
apiVersion: v1
kind: List
metadata:
items: 
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: net-test-server
    name: net-test-server
  spec:
    selector:
      matchLabels:
        app: net-test-server
    replicas: 3
    revisionHistoryLimit: 3
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: net-test-server
      spec:
        containers:
        - image: theog75/sdntestclient:v1
          imagePullPolicy: Always
          name: net-test-server
          ports:
          - containerPort: 8080
            protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: net-test-server
    name: net-test-server
  spec:
    ports:
    - name: http
      port: 8088
      protocol: TCP
      targetPort: 8088
    selector:
      app: net-test-server
    sessionAffinity: None
    type: ClusterIP

- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: net-test-client
    name: net-test-client
  spec:
    selector:
      matchLabels:
        app: net-test-client
    replicas: 1
    revisionHistoryLimit: 3
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: net-test-client
      spec:
        containers:
        - env:
          - name: DELAYVAR
            value: "200ms"
          - name: FORK
            value: "1"
          - name: DEST
            value: "http://net-test-server:8080/ping"
          image: theog75/sdntestclient:v1
          imagePullPolicy: Always
          name: net-test-server
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        
